name: deploy-auth

on:
  push:
    branches: 
      - main
    paths:
      - 'auth/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t jitusehrawat/auth .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push jitusehrawat/auth
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing

      - uses: actions/checkout@v2

      - run: kubectl apply -f infra/k8s/auth-depl.yaml -f infra/k8s/auth-mongo-depl.yaml && kubectl apply -f infra/k8s-prod -f infra/k8s/nats-depl.yaml