# This is a basic workflow to help you get started with Actions

name: deploy-client

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
    paths:
      - 'client/*'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build images
        run: cd client && docker build -t jitusehrawat/client .

      # Runs a set of commands using the runners shell
      - name: Login to Docker
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      # Runs a single command using the runners shell
      - name: Push Image to dockerHub
        run: docker push jitusehrawat/client
        
      # Runs a single command using the runners shell
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          
      # Runs a single command using the runners shell
      - name: Setting up kubeconfig context
        run: doctl kubernetes cluster kubeconfig save ticketing
        
      # Runs a single command using the runners shell
      - name: Updating the deployment to use latest image
        run: kubectl rollout restart deployment client-depl
